# Generated by Django 3.1.7 on 2021-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='carousel_home/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='news_home/')),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
